USB_VID = 0x2E8A
USB_PID = 0x101F

USB_INTERFACE_NAME = "AGracing KeyPad 20"

USB_PRODUCT = "Keypad 20"
USB_MANUFACTURER = "AGracing"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY__EVE = 1
